### ISSUE TITLE
Half-online-mode: The player's movement speed won't restore after auto-login

### ISSUE THREAD

**Issue by NorbiPeti** [NorbiPeti/thebuttonautoflairmc#7]
Apparently it does restore, sometimes.

**Comment by NorbiPeti** [comment]
And when it does, it does with a NullPointerException.

`java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.7.0_79]
        at java.util.concurrent.FutureTask.get(FutureTask.java:188) ~[?:1.7.0_79]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:46) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:437) ~[spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.PacketPlayInTeleportAccept.a(SourceFile:31) ~[spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.PacketPlayInTeleportAccept.a(SourceFile:8) ~[spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[?:1.7.0_79]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[?:1.7.0_79]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) ~[spigot-1.9.jar:git-Spigot-d20369f-7fc5cd8]
        ... 5 more
`

Also, added a temporary fix.
